# Generated by Django 4.2 on 2024-04-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_volunteerrecruitment_volunteerlist_distribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerrecruitment',
            name='participant_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
